services:
  # Backend (Go)
  - type: web
    name: codedrop-backend
    env: go
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: go build -o app main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: codedrop-db
          property: connectionString
      - key: REDIS_URL
        sync: false

  # Frontend (Next.js)
  - type: web
    name: codedrop-frontend
    env: node
    region: frankfurt
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_HOST
        fromService:
          type: web
          name: codedrop-backend
          property: host

databases:
  - name: codedrop-db
    databaseName: codedrop
    user: codedrop
    plan: free
    region: frankfurt
